keys:
  - &biome-fest age1ak36zs98fj3eu3ysuc7krzh44fx5t6sf0plvqmmg3z0mqpg2vp5qqkvr4y
  - &blind-spots age1r3yll2yy4mpf7s6wew8ywsw4lxkfvmk73acsmpjnrqgunnnunsfqgtddxh
  - &dead-voxel age1he8wrq7e7ae52rf7r2pjanyexcy9ku02hxwqctuz8fzujlx5tswqxln7cm
  - &dreiton age1fd03mf7k5xcmzh4gjx903z6z92ydx2yqwndhakgh585cdqjrgscqt5pnph
  - &floating-trees age1h5pt2695wwlgv6n703araqy4gphmwry9uz7udwqvezwftqtzt9squcefj4
  - &haunt-muskie age18ay0p4gm2jqam6zgz9pxk27jtft3fnz3560m6naz47j2yaf0hadq0za492
  - &wet-hands age1yusne4xuc6du0qgfumrr6pxj5htq38ug806tda4tkg7du48dlcjqymr086
creation_rules:
  - path_regex: hosts/biome-fest/secrets.yaml$
    key_groups:
      - age:
          - *biome-fest
  - path_regex: hosts/blind-spots/secrets.yaml$
    key_groups:
      - age:
          - *blind-spots
  - path_regex: hosts/dead-voxel/secrets.yaml$
    key_groups:
      - age:
          - *dead-voxel
  - path_regex: hosts/dreiton/secrets.yaml$
    key_groups:
      - age:
          - *dreiton
  - path_regex: hosts/floating-trees/modules/drives/secrets.yaml$
    key_groups:
      - age:
          - *floating-trees
  - path_regex: hosts/floating-trees/secrets.yaml$
    key_groups:
      - age:
          - *floating-trees
  - path_regex: hosts/haunt-muskie/secrets.yaml$
    key_groups:
      - age:
          - *haunt-muskie
  - path_regex: hosts/wet-hands/secrets.yaml$
    key_groups:
      - age:
          - *wet-hands
  - path_regex: modules/home/git/secrets.yaml$
    key_groups:
      - age:
          - *biome-fest
          - *dead-voxel
  - path_regex: modules/home/helix/secrets.yaml$
    key_groups:
      - age:
          - *biome-fest
          - *dead-voxel
  - path_regex: modules/home/uni/secrets.yaml$
    key_groups:
      - age:
          - *biome-fest
          - *dead-voxel
  - path_regex: modules/nixos/hoglin-drive/secrets.yaml$
    key_groups:
      - age:
          - *biome-fest
          - *dead-voxel
  - path_regex: modules/nixos/llm-tools/secrets.yaml$
    key_groups:
      - age:
          - *biome-fest
          - *dead-voxel
  - path_regex: modules/nixos/nix-access-tokens/secrets.yaml$
    key_groups:
      - age:
          - *biome-fest
          - *dead-voxel
  - path_regex: modules/nixos/porkbunAcme/secrets.yaml$
    key_groups:
      - age:
          - *floating-trees
          - *haunt-muskie
  - path_regex: modules/nixos/shared/network/services/actual/secrets.yaml$
    key_groups:
      - age:
          - *floating-trees
  - path_regex: modules/nixos/shared/network/services/authelia/secrets.yaml$
    key_groups:
      - age:
          - *floating-trees
  - path_regex: modules/nixos/shared/network/services/headscale/secrets.yaml$
    key_groups:
      - age:
          - *haunt-muskie
  - path_regex: modules/nixos/shared/network/services/jellyfin/secrets.yaml$
    key_groups:
      - age:
          - *floating-trees
  - path_regex: modules/nixos/shared/network/services/librechat/secrets.yaml$
    key_groups:
      - age:
          - *floating-trees
  - path_regex: modules/nixos/shared/network/services/llamacpp/secrets.yaml$
    key_groups:
      - age:
          - *dead-voxel
          - *floating-trees
  - path_regex: modules/nixos/shared/network/services/lldap/secrets.yaml$
    key_groups:
      - age:
          - *floating-trees
          - *haunt-muskie
  - path_regex: modules/nixos/shared/network/services/mealie/secrets.yaml$
    key_groups:
      - age:
          - *floating-trees
  - path_regex: modules/nixos/shared/network/services/paperless/secrets.yaml$
    key_groups:
      - age:
          - *floating-trees
  - path_regex: modules/nixos/shared/network/services/vikunja/secrets.yaml$
    key_groups:
      - age:
          - *floating-trees
  - path_regex: modules/nixos/shared/network/vpn/secrets.yaml$
    key_groups:
      - age:
          - *biome-fest
          - *blind-spots
          - *dead-voxel
          - *dreiton
          - *floating-trees
          - *haunt-muskie
          - *wet-hands
  - path_regex: modules/nixos/uni-vpn/secrets.yaml$
    key_groups:
      - age:
          - *biome-fest
          - *dead-voxel
  - path_regex: users/osi/secrets.yaml$
    key_groups:
      - age:
          - *biome-fest
          - *dead-voxel
