# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usbhid"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/mapper/luks-eded9eca-c0eb-4474-a0b5-1103acf72ed4";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-eded9eca-c0eb-4474-a0b5-1103acf72ed4".device = "/dev/disk/by-uuid/eded9eca-c0eb-4474-a0b5-1103acf72ed4";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/A840-373E";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
